### PR TITLE
FIXED IT MERGE IT PLS

### PR DESCRIPTION
**Pull request by Tavrie**
YAYAYAYYAYAYAAY  (changing the history flooder to act like the students are in the website that are there suppose to be)

### CODE REVIEW

**Comment by ingoau** [comment]
doesn't look finished. not sure what this pr is doing
image
image

**Comment by Tavrie** [comment]
> doesn't look finished. not sure what this pr is doing
> 
> image
> 
> image
> 
> 

That's weird

**Comment by Tavrie** [comment]
Do you have discord?

**Comment by ingoau** [comment]
Still don't know why this is needed

**Comment by Tavrie** [comment]
> Still don't know why this is needed

Just incase

**Comment by ingoau** [comment]
I'm currently not maintaining this project so you can continue your own in a fork

**Pull request closed without merging**
